version: "3.9"

services:

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MARIADB_USER: user
      MARIADB_PASSWORD: user
      MARIADB_DATABASE: db_polls
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ejercicios_django/mysite/:/code
    ports:
      - "8000:8000"
    depends_on:
        - db

volumes:
  mariadb:
